project:
  type: website
  resources:
    - fonts
  preview:
    port: 4322

execute:
  freeze: auto
  
website:
  title: "Advent of Code by Francisco Yirá"
  #site-url: https://github.com
  description: My solutions to Advent of Code
  repo-url: https://github.com/franciscoyira/advent-of-code-website
  navbar:
    left:
     - 2023.qmd
    right:
      - href: https://www.franciscoyira.com/
        text: "blog"
        rel: external
      - href: https://www.franciscoyira.com/subscribe
        text: "newsletter"
      - href: https://cv.franciscoyira.com/
        text: "portfolio"
      - icon: github
        href: https://github.com/franciscoyira/advent-of-code-website
      - icon: linkedin
        href: https://www.linkedin.com/in/franciscoyira/
      - icon: mastodon
        href: https://techhub.social/home
  open-graph: true

format:
  html:
    theme: 
      dark: custom-dark.scss
      light: [cosmo, custom-light.scss]
    css: styles.css
    code-block-border-left: true
    smooth-scroll: true
    link-external-newwindow: true

editor: source



