{
  "hash": "0114a9ff2ea8e25d41f5ca4ce579950a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"2023: Day 7\"\ndate: 2023-12-7\ncategories:\n  - python\ndraft: true\n---\n\n## Setup\n\n[The original challenge](https://adventofcode.com/2023/day/7)\n\n[My data](input){target=\"_blank\"}\n\nNotes:\n\n-   Desert Island uses machines to make sand out of rocks but the machines have broken down because they stopped receiving parts needed to fix the machines.\n-   Have to play Camel Cards during the journey to figure out why the parts stopped.\n\n> In Camel Cards, you get a list of hands, and your goal is to order them based on the strength of each hand. A hand consists of five cards labeled one of A, K, Q, J, T, 9, 8, 7, 6, 5, 4, 3, or 2. The relative strength of each card follows this order, where A is the highest and 2 is the lowest.\n\n> Every hand is exactly one type. From strongest to weakest, they are:\n\n> -   Five of a kind, where all five cards have the same label: AAAAA\n>\n> -   Four of a kind, where four cards have the same label and one card has a different label: AA8AA\n>\n> -   Full house, where three cards have the same label, and the remaining two cards share a different label: 23332\n>\n> -   Three of a kind, where three cards have the same label, and the remaining two cards are each different from any other card in the hand: TTT98\n>\n> -   Two pair, where two cards share one label, two other cards share a second - label, and the remaining card has a third label: 23432\n>\n> -   One pair, where two cards share one label, and the other three cards have a different label from the pair and each other: A23A4\n>\n> -   High card, where all cards' labels are distinct: 23456\n\n- Hands are ordered first by type.\n\n- Then, the following rule applies:\n\n> Start by comparing the first card in each hand. If these cards are different, the hand with the stronger first card is considered stronger. If the first card in each hand have the same label, however, then move on to considering the second card in each hand. If they differ, the hand with the higher second card wins; otherwise, continue with the third card in each hand, then the fourth, then the fifth.\n\n> So, 33332 and 2AAAA are both four of a kind hands, but 33332 is stronger because its first card is stronger. Similarly, 77888 and 77788 are both a full house, but 77888 is stronger because its third card is stronger (and both hands have the same first and second card).\n\nAlso, there is a *bid* for each hand. In the example input:\n\n```\n32T3K 765\nT55J5 684\nKK677 28\nKTJJT 220\nQQQJA 483\n```\n\n> Each hand wins an amount equal to its bid multiplied by its rank, where the weakest hand gets rank 1, the second-weakest hand gets rank 2, and so on up to the strongest hand. Because there are five hands in this example, the strongest hand will have rank 5 and its bid will be multiplied by 5.\n\nIn this example, first we need to put the hands in order of strength.\n\n> - 32T3K is the only one pair and the other hands are all a stronger type, so it gets rank 1.\n> - KK677 and KTJJT are both two pair. Their first cards both have the same label, but the second card of KK677 is stronger (K vs T), so KTJJT gets rank 2 and KK677 gets rank 3.\n> - T55J5 and QQQJA are both three of a kind. QQQJA has a stronger first card, so it gets rank 5 and T55J5 gets rank 4.\n\nTotal winnings = (765 * 1 + 220 * 2 + 28 * 3 + 684 * 4 + 483 * 5) = 6440.\n\nNow I have to do the same with [my data](input){target=\"_blank\"}.\n\n## Part 1\n\n::: {#4a4f451b .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\n```\n:::\n\n\n### Importing the data\n\nLoading the data into a `numpy` array\n\n::: {#214105f1 .cell execution_count=2}\n``` {.python .cell-code}\ninput = np.loadtxt('input', dtype = 'object')\ninput[:10]\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\narray([['99898', '978'],\n       ['T99A9', '198'],\n       ['43Q34', '550'],\n       ['KK8QK', '418'],\n       ['Q6Q57', '767'],\n       ['35A37', '832'],\n       ['AJ867', '137'],\n       ['45679', '936'],\n       ['8TJ88', '409'],\n       ['7772T', '208']], dtype=object)\n```\n:::\n:::\n\n\nWhat data structure do I want?\n- two lists, one with the cards, another one with the bids.\n- Alternatively, one dataframe\n\n::: {#7ef9a5c5 .cell execution_count=3}\n``` {.python .cell-code}\ncards = list(input[:, 0])\nbids = list(map(int, list(input[:, 1])))\n```\n:::\n\n\n### Ranking the hands\n\nOne straightforward approach here is to assign points to the hands based on the rules and then sort/rank based on those points.\n\nThe algorithm should be something like this:\n\n1. Identify the TYPE of the hand: five of a kind > four of a kind > full house > three of a kind > two pair > one pair > high card. Assign points based on that.\n2. Then, assign points based on the value of each of the cards of the hand, from left to right, using this sorting: (highest score) A, K, Q, J, T, 9, 8, 7, 6, 5, 4, 3, 2 (lowest score).\n\nA reasonable way of doing this would be to create a column with the points based on type, and then one column to the right for each of the cards of the hand, indicating the points corresponding to that card. Finally, perform a `sort_values()`, first by type, and then consecutively breaking ties using the columns to the right.\n\n### Function to get points based on type\n\nI'll start by solving for a particular case:\n\nHelper function:\n\n::: {#0710262b .cell execution_count=4}\n``` {.python .cell-code}\ndef n_distinct_cards(hand):\n  return len(set(list(hand)))\n```\n:::\n\n\n::: {#029123cc .cell execution_count=5}\n``` {.python .cell-code}\nfrom collections import Counter\n\nexample_card = 'AAAAA'\n\n# identify Five of a Kind\nmy_n_diff_cards = n_distinct_cards(example_card)\nmax_n_cards = max(Counter(list(example_card)).values())\n```\n:::\n\n\n::: {#87b91a1b .cell execution_count=6}\n``` {.python .cell-code}\nif (my_n_diff_cards == 1):\n  print('Five of a kind')\nelif (my_n_diff_cards == 2):\n  # In this case, the hand could either be four of a kind or full house\n  if (max_n_cards == 4):\n    print('Four of a kind')\n  else:\n    print('Full house')\nelif (my_n_diff_cards == 3):\n  # could be: three of a kind OR two pair\n  if (max_n_cards == 3):\n    print('Three of a kind')\n  else:\n    print('Two pair')\nelif (my_n_diff_cards == 4):\n  print('One pair')\nelse:\n  print('High card')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFive of a kind\n```\n:::\n:::\n\n\nI tested this with all the examples and works as it should. Now I'll wrap it into a function that assignes points \n\n::: {#fa3f9a39 .cell execution_count=7}\n``` {.python .cell-code}\ndef points_by_type(hand):\n  my_n_diff_cards = n_distinct_cards(hand)\n  max_n_cards = max(Counter(list(hand)).values())\n\n  if (my_n_diff_cards == 1):\n    #'Five of a kind'\n    return 7\n  elif (my_n_diff_cards == 2):\n    # In this case, the hand could either be four of a kind or full house\n    if (max_n_cards == 4):\n      # Four of a kind\n      return 6\n    else:\n      return 5\n  elif (my_n_diff_cards == 3):\n    # could be: three of a kind OR two pair\n    if (max_n_cards == 3):\n      # Three of a kind\n      return 4\n    else:\n      # Two pair\n      return 3\n  elif (my_n_diff_cards == 4):\n    # One pair\n    return 2\n  else:\n    # High card\n    return 1\n```\n:::\n\n\nTesting with the actual cards:\n\n::: {#fdbe9589 .cell execution_count=8}\n``` {.python .cell-code}\nlist(map(points_by_type, cards))[1:10]\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\n[4, 3, 4, 2, 2, 1, 1, 4, 4]\n```\n:::\n:::\n\n\n(I think should store the cards and the points as a `pandas` dataframe)\n\n### Function to get the points based on the cards\n\n::: {#860ff4b1 .cell execution_count=9}\n``` {.python .cell-code}\nkinds_cards = list(\"AKQJT98765432\"[::-1])\nkinds_cards\n\nmy_card = 'A'\npoints_by_card = kinds_cards.index(my_card)\npoints_by_card\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\n12\n```\n:::\n:::\n\n\n::: {#d55c494b .cell execution_count=10}\n``` {.python .cell-code}\n# Trying to obtain a sorting score for the hand using all the cards at once\nkinds_cards = list(\"AKQJT98765432\"[::-1])\ndef points_by_card(hand):\n  points_by_cards = 0\n  my_cards = list(hand)\n\n  for card in my_cards:\n    points_by_cards = points_by_cards*13 + kinds_cards.index(card)\n\n  return points_by_cards\n```\n:::\n\n\n::: {#121dbb88 .cell execution_count=11}\n``` {.python .cell-code}\ndf = pd.DataFrame({\n  'hands': cards,\n  'bids': bids\n})\n\ndf\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>hands</th>\n      <th>bids</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>99898</td>\n      <td>978</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>T99A9</td>\n      <td>198</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>43Q34</td>\n      <td>550</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>KK8QK</td>\n      <td>418</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Q6Q57</td>\n      <td>767</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>995</th>\n      <td>QQQ78</td>\n      <td>524</td>\n    </tr>\n    <tr>\n      <th>996</th>\n      <td>AAAA7</td>\n      <td>190</td>\n    </tr>\n    <tr>\n      <th>997</th>\n      <td>QQ222</td>\n      <td>899</td>\n    </tr>\n    <tr>\n      <th>998</th>\n      <td>7K283</td>\n      <td>284</td>\n    </tr>\n    <tr>\n      <th>999</th>\n      <td>23339</td>\n      <td>728</td>\n    </tr>\n  </tbody>\n</table>\n<p>1000 rows × 2 columns</p>\n</div>\n```\n:::\n:::\n\n\n::: {#acaecec1 .cell execution_count=12}\n``` {.python .cell-code}\ndf1 = df.assign(\n  points_type = list(map(points_by_type, df.hands)),\n  points_cards = list(map(points_by_card, df.hands)))\\\n    .sort_values(by = ['points_type', 'points_cards'])\n```\n:::\n\n\n::: {#bb451f09 .cell execution_count=13}\n``` {.python .cell-code}\ndf1.reset_index(drop = True, inplace = True)\ndf1['rank'] = df1.index + 1\n```\n:::\n\n\n::: {#4c82595c .cell execution_count=14}\n``` {.python .cell-code}\nsum(df1[\"bids\"] * df1[\"rank\"])\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\n246163188\n```\n:::\n:::\n\n\nMy solution is correct!\n\n## Part 2\n\n> Now, J cards are jokers - wildcards that can act like whatever card would make the hand the strongest type possible.\n\n> To balance this, J cards are now the weakest individual cards, weaker even than 2. The other cards stay in the same order: A, K, Q, T, 9, 8, 7, 6, 5, 4, 3, 2, J.\n\nImplementing this change in `points_by_card` is straightforward. Just need to re-arrange the list that maps the cards to their scores.\n\n::: {#8917c2d1 .cell execution_count=15}\n``` {.python .cell-code}\nkinds_cards = list(\"AKQT98765432J\"[::-1])\n```\n:::\n\n\nBut I suspect that addressing this new logic in the `points_by_type` function will be more complicated. For each joker, we have to explore what is, potentially, the best type each hand could be if we could swap that card for any other.\n\nIdea: use as input the N of jokers and the hand type without the jokers rule.\n\n- Five of a kind > can't get any better\n- Four of a kind > two scenarios \n    - 4 jokers: the can turn into the card with different level. Type goes up to Five of a kind.\n    - 1 joker: it can turn into the kind of the other 4 cards. Type goes up too.\n- Full house > two scenarios\n    - 3 jokers: becomes five of a kind\n    - 2 jokers: becomes five of a kind\n- Three of a kind > two scenarios\n    - 3 jokers: becomes four of a kind\n    - 1 joker: becomes four of a kind\n- Two pair > two scenarios\n    - 2 jokers: becomes four of a kind\n    - 1 joker: becomes full house\n- One pair > two scenarios\n    - 2 jokers: becomes three of a kind\n    - 1 joker: becomes three of a kind\n- High card > by definition there can only by up to one joker. In that case, hand becomes \"one pair\".\n\nSo, based on the number of jokers and the initial type of the card, we can infer how the type of the hand is going to change with these new rules.\n\n::: {#82960484 .cell execution_count=16}\n``` {.python .cell-code}\ndef new_type(points_type, n_jokers):\n  if n_jokers == 0 or points_type == 7:\n    return points_type\n\n  # Four of a kind becomes five of a kind\n  if points_type == 6:\n    return 7\n\n  # Full house becomes five of a Kind\n  if points_type == 5:\n    return 7\n\n  # Three of a kind becomes four of a kind\n  if points_type == 4:\n    return 6\n\n  # Two pair can become four of a kind or full house\n  if points_type == 3:\n    if n_jokers == 2:\n      return 6\n    else:\n      return 5\n  \n  # One pair becomes three of a kind\n  if points_type == 2:\n    return 4\n\n  # High card becomes one pair\n  if points_type == 1:\n    return 2\n```\n:::\n\n\nI also need a function that counts jokers:\n\n::: {#50120004 .cell execution_count=17}\n``` {.python .cell-code}\nexample_card = 'JAJAJ'\nCounter(list(example_card))['J']\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```\n3\n```\n:::\n:::\n\n\n::: {#31cc290d .cell execution_count=18}\n``` {.python .cell-code}\ndef joker_counter(hand):\n  return Counter(list(hand))['J']\n```\n:::\n\n\n::: {#3fd5fc0d .cell execution_count=19}\n``` {.python .cell-code}\ndf1 = df1.assign(\n  n_jokers = list(map(joker_counter, df1.hands)))\n```\n:::\n\n\n::: {#cf852133 .cell execution_count=20}\n``` {.python .cell-code}\ndf1 = df1.assign(\n  new_points_type = list(map(new_type, df1.points_type, df1.n_jokers)),\n  # Here I can apply the same function as before because I changed the value of kinds_cards\n  new_points_cards = list(map(points_by_card, df1.hands))\n)\n```\n:::\n\n\n::: {#f637940c .cell execution_count=21}\n``` {.python .cell-code}\ndf2 = df1.sort_values(by = ['new_points_type', 'new_points_cards'])\\\n  .reset_index(drop = True)\n\n\ndf2['rank'] = df2.index + 1\n```\n:::\n\n\n::: {#01c26e59 .cell execution_count=22}\n``` {.python .cell-code}\nsum(df2[\"bids\"] * df2[\"rank\"])\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```\n245794069\n```\n:::\n:::\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}